# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../prophesee_1meg/images/trainfilelist00_every30/
val: ../prophesee_1meg/images/trainfilelist00_every30/  # 128 images

# number of classes
nc: 7

# class names
names: ['pedestrians', 'two-wheelers', 'cars', 'trucks', 'buses', 'traffic-signs', 'traffic-lights']